spring:
    application:
        name: kafka-demo

server:
    port: 9001

kafka:
    bootstrap-servers: localhost:9092
    sasl:
        enabled: true
        username: demo
        password: demo-password
    inboundTopic: "demo-inbound-topic"
    outboundTopic: "demo-outbound-topic"

